name: cicd-dev
on:
  workflow_dispatch:
jobs:
  test:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  continuous-integration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run-script build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build artifacts
          path: |
            build
            package.json
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build artifacts
      - name: show folder
        run: ls
      - name: Deploy to github pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
